package com.llat.models;
public enum AlgorithmType {
    GENERAL,
    CLOSED_TREE_DETERMINER,
    LOGICAL_FALSEHOOD_DETERMINER,
    LOGICALLY_CONTINGENT_DETERMINER,
    LOGICAL_TAUTOLOGY_DETERMINER,
    MAIN_OPERATOR_DETECTOR,
    OPEN_TREE_DETERMINER,
    LOGICALLY_CONTRADICTORY_DETERMINER,
    LOGICALLY_CONSISTENT_DETERMINER,
    LOGICALLY_CONTRARY_DETERMINER,
    LOGICALLY_EQUIVALENT_DETERMINER,
    LOGICALLY_IMPLIED_DETERMINER,
    ARGUMENT_TRUTH_TREE_VALIDATOR,

    PROPOSITIONAL,
    PROPOSITIONAL_TRUTH_TREE_GENERATOR,
    RANDOM_FORMULA_GENERATION,
    TRUTH_TABLE_GENERATOR,

    PREDICATE,
    BOUND_VARIABLE_DETECTOR,
    CLOSED_SENTENCE_DETERMINER,
    FREE_VARIABLE_DETECTOR,
    GROUND_SENTENCE_DETERMINER,
    OPEN_SENTENCE_DETERMINER,
    PREDICATE_TRUTH_TREE_GENERATOR,

    NULL
}
